name: Correct Design Token References

on:
  push:
    paths:
      - 'btokens (3).json' # Adjust this to your token file(s) path

jobs:
  correct_tokens:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or a version you prefer

    - name: Install dependencies (if any)
      run: |
        python -m pip install --upgrade pip
        # Add any Python dependencies here if needed (e.g., requests)

    - name: Correct Token References
      run: |
        python correct_tokens.py # Or the name of your python script

    - name: Commit changes (if any)
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Fix: Corrected design token references"
        file_pattern: 'btokens (3).json' # Only commit the corrected token file